apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: igyxc2gnn-nodejs 
  janus-idp.io/tekton: igyxc2gnn-nodejs
  backstage.io/kubernetes-id: igyxc2gnn-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: igyxc2gnn-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  