apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: igyxc2gnn-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: igyxc2gnn-nodejs 
  name: igyxc2gnn-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: igyxc2gnn-nodejs 
